// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bjzlyaubviztewmdittl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJqemx5YXVidml6dGV3bWRpdHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNjMyNjAsImV4cCI6MjA3MjczOTI2MH0.gXFF_u4X-bEQ2r4njZWyh93dm_0kj0gGRY44OqEvbLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});